name: 👊 Bump Version & Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: 👊 Bump Version & Release
    runs-on: ubuntu-latest
    # this workflow will run only if commit message ends with "RELEASE"
    if: "contains(github.event.head_commit.message, 'RELEASE')"
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
      - name: cat package.json
        run: cat ./package.json

      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1
        with:
          private_key: ${{ secrets.APP_PEM }}
          app_id: ${{ secrets.APP_ID }}

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: release/v
          major-wording: 'MAJOR'
          minor-wording: 'MINOR'
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
      - name: cat package.json
        run: cat ./package.json
      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
